---
title: "Figures_peers"
author: "Camila Scaff"
date: "5/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(scales)
library(gridExtra)
library(ggpubr)
library(reshape2)
library(dplyr)

#read the right tables
read.csv("demuth_speakers.txt", sep = "") -> sum_demuth_tot #contains unclassified speech and investigator
read.delim("results_Rmd/french_speakers.txt", sep = "") -> sum_french_tot #contains unclassified speech and investigator
read.delim("results_Rmd/french_register.txt", sep = "") -> tot_sum_french_register # contains unclassified speech but only agreement between coders
read.delim("results_Rmd/demuth_register.txt", sep = "") -> tot_sum_demuth_register# contains unclassified speech but only agreement between coders
table(sum_demuth_tot$keychild,sum_demuth_tot$speaker) #check
#create the lines (this should be done via a loop sorry!)
peer_Hlo <- data.frame("sibling","Hlobohang", "0")
#names the lines
names(peer_Hlo)<-c("speaker","keychild", "nb_utt")
#added to the main data.frame
sum_demuth_tot <- rbind(sum_demuth_tot, peer_Hlo)

sum_demuth_tot$nb_utt <- as.numeric(sum_demuth_tot$nb_utt)

```

```{r functions, echo=F}
#defining multiplot to create easy panels
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  if (numPlots==1) {
    print(plots[[1]])
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )
```


Snap Shot of the different speakers in the corpora
```{r hundredpercent, echo=F}
##determine 100%
total_demuth<-sum(sum_demuth_tot$nb_utt) #69573
total_french<-sum(sum_french_tot$nb_utt) #37843

## determine 100% of speakers REMOVING keychild production
tot_speaker_demuth<-sum(sum_demuth_tot$nb_utt[sum_demuth_tot$speaker== "Target_Child"]) #28853
tot_speaker_demuth*100/total_demuth -> d_perc_TC #41.5%

tot_speaker_french<-sum(sum_french_tot$nb_utt[sum_french_tot$speaker== "Target_Child"]) #16338
tot_speaker_french*100/total_french -> fr_perc_TC #42.6%

inv_speaker_demuth<-sum(sum_demuth_tot$nb_utt[sum_demuth_tot$speaker== "investigator"]) #5486
inv_speaker_demuth*100/total_demuth -> d_perc_INV #7.9%

inv_speaker_french<-sum(sum_french_tot$nb_utt[sum_french_tot$speaker== "investigator"]) #2333
inv_speaker_french*100/total_french -> fr_perc_INV #6.1%

a_speaker_demuth<-sum(sum_demuth_tot$nb_utt[sum_demuth_tot$speaker== "adult"]) #6705
a_speaker_demuth*100/total_demuth -> d_perc_A#9.6%

a_speaker_french<-sum(sum_french_tot$nb_utt[sum_french_tot$speaker== "adult"]) #2137
a_speaker_french*100/total_french -> fr_perc_A #5.6%

m_speaker_demuth<-sum(sum_demuth_tot$nb_utt[sum_demuth_tot$speaker== "mother"]) #10283
m_speaker_demuth*100/total_demuth -> d_perc_M #14.8%

m_speaker_french<-sum(sum_french_tot$nb_utt[sum_french_tot$speaker== "mother"]) # 15706
m_speaker_french*100/total_french -> fr_perc_M #41%

peer_speaker_demuth<-sum(sum_demuth_tot$nb_utt[sum_demuth_tot$speaker== "peer"]) #12047
peer_speaker_demuth*100/total_demuth -> d_perc_PEER #17.3%

peer_speaker_french<-sum(sum_french_tot$nb_utt[sum_french_tot$speaker== "other child"]) #6199
peer_speaker_french*100/total_french -> fr_perc_PEER #4.8%

sib_speaker_demuth<-sum(sum_demuth_tot$nb_utt[sum_demuth_tot$speaker== "sibling"]) #28853
sib_speaker_demuth*100/total_demuth -> d_perc_SIB #9%


#SNAPSHOT
wholeset <- data.frame(
  corpus=c("Sesotho", "French","Sesotho", "French","Sesotho", "French","Sesotho", "French","Sesotho","French","Sesotho"), 
  production=c("Target Child","Target Child", "Adults","Adults", "Mother", "Mother", "Investigator", "Investigator","Other Children","Other Children","Siblings"), 
  utt=c(tot_speaker_demuth, tot_speaker_french, a_speaker_demuth, a_speaker_french, m_speaker_demuth,m_speaker_french, inv_speaker_demuth, inv_speaker_french, peer_speaker_demuth, peer_speaker_french, sib_speaker_demuth),
  value= c(d_perc_TC, fr_perc_TC,d_perc_A,fr_perc_A,d_perc_M,fr_perc_M,d_perc_INV,fr_perc_INV,d_perc_PEER,fr_perc_PEER,d_perc_SIB))


Sesotho <- ggplot(subset(wholeset, corpus %in% c("Sesotho")), aes (x="", y = value, fill = production)) + geom_col(position = 'stack', width = 1,color="white") +geom_text(aes(label = paste(round(value,1), "%"), x = 1.3),position = position_stack(vjust = 0.5)) + theme_classic() +theme(plot.title = element_text(hjust=0.5),axis.line = element_blank(),axis.text = element_blank(),axis.ticks = element_blank()) + labs(fill = "Speaker", x = NULL,y = NULL,title = "Sesotho") + coord_polar("y")

French <- ggplot(subset(wholeset, corpus %in% c("French")), aes (x="", y = value, fill = production)) + geom_col(position = 'stack', width = 1,color="white") +geom_text(aes(label = paste(round(value,1), "%"), x = 1.3),position = position_stack(vjust = 0.5)) + theme_classic() +theme(plot.title = element_text(hjust=0.5),axis.line = element_blank(),axis.text = element_blank(),axis.ticks = element_blank()) + labs(fill = "Speaker", x = NULL,y = NULL,title = "French") + coord_polar("y")

ggarrange(Sesotho, French, ncol=2, nrow=1, common.legend = TRUE, legend="right")

```

## Distribution of speaker by corpus and keychild 
```{r screening, echo=F}
#choose to remove Investigator // this is important for calculating percentages
#Remove investigator, unclassified speech
sum_demuth_register<-subset(tot_sum_demuth_register, !(tot_sum_demuth_register$speaker=="investigator"))
sum_demuth_register<-subset(sum_demuth_register, !(sum_demuth_register$input=="unclassified"))
sum_demuth_register<-subset(sum_demuth_register, !(sum_demuth_register$input=="Investigator"))

sum_french_register<-subset(tot_sum_french_register, !(tot_sum_french_register$speaker=="investigator"))
sum_french_register<-subset(sum_french_register, !(sum_french_register$input=="unclassified"))
sum_french_register<-subset(sum_french_register, !(sum_french_register$input=="Investigator"))
```

##SNAPSHOT WITHOUT Target child  and merging peer + sibling in demuth
````{r fig1, echo=F}
ggfillsesotho <-  ggplot(tot_sum_demuth_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="fill")+  labs(x="Sesotho", y="Number of utterances") + guides(fill=FALSE) + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme + geom_text(aes(label = nb_utt), position = position_stack(vjust = 0.5), size = 2)

ggfillfrench <- ggplot(tot_sum_french_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="fill")+  labs(x="Sesotho", y="Number of utterances")   + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

ggarrange(ggfillsesotho, ggfillfrench, ncol=2, nrow=1, common.legend = TRUE, legend="right",  labels = c("Sesotho", "French"))

ggrawsesotho <-  ggplot(tot_sum_demuth_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Sesotho", y="Number of utterances") + guides(fill=FALSE) + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

ggrawfrench <- ggplot(tot_sum_french_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Sesotho", y="Number of utterances")   + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

ggarrange(ggrawsesotho, ggrawfrench, ncol=2, nrow=1, common.legend = TRUE, legend="right",  labels = c("Sesotho", "French"))

kch_french <- ggplot(tot_sum_french_register, aes( y=nb_utt, x=keychild, fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Keychild", y="Number of utterances")
kch_demuth <- ggplot(tot_sum_demuth_register, aes( y=nb_utt, x=keychild, fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Keychild", y="Number of utterances")+ guides(fill=FALSE)

ggarrange(kch_demuth, kch_french, ncol=2, nrow=1, common.legend = TRUE, legend="right", labels = c("Sesotho", "French"))

```

Without investigator
```{r fig2}
gg2fillsesotho <-  ggplot(sum_demuth_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="fill")+  labs(x="Sesotho", y="Number of utterances") + guides(fill=FALSE) + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

gg2fillfrench <- ggplot(sum_french_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="fill")+  labs(x="Sesotho", y="Number of utterances")   + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

ggarrange(gg2fillsesotho, gg2fillfrench, ncol=2, nrow=1, common.legend = TRUE, legend="right",  labels = c("Sesotho", "French"))

gg2rawsesotho <-  ggplot(sum_demuth_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Sesotho", y="Number of utterances") + guides(fill=FALSE) + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

gg2rawfrench <- ggplot(sum_french_register, aes( y=nb_utt, x="", fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Sesotho", y="Number of utterances")   + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

ggarrange(gg2rawsesotho, gg2rawfrench, ncol=2, nrow=1, common.legend = TRUE, legend="right",  labels = c("Sesotho", "French"))

kch_french <- ggplot(sum_french_register, aes( y=nb_utt, x=keychild, fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Keychild", y="Number of utterances")  + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme
kch_demuth <- ggplot(sum_demuth_register, aes( y=nb_utt, x=keychild, fill=speaker))+geom_bar(stat="identity", position="dodge")+  labs(x="Keychild", y="Number of utterances")+ guides(fill=FALSE)  + scale_fill_discrete(labels= c("Adults", "Investigator", "Mother", "Other children")) + blank_theme

ggarrange(kch_demuth, kch_french, ncol=2, nrow=1, common.legend = TRUE, legend="right", labels = c("Sesotho", "French"))

```

```{r demuth for figure purposes, echo=F}
######checked up to here -g
library(reshape2)
# #add label of type of input
# sum_demuth_ADS$input <- "ADS"
# sum_demuth_CDS$input <- "CDS"
# 
# #remove for CDS the target child utterances in which he is talking to himself
# sum_demuth_CDS<-subset(sum_demuth_CDS, !(sum_demuth_CDS$speaker=="Target_Child"))
# sum_demuth_ADS<-subset(sum_demuth_ADS, !(sum_demuth_ADS$speaker=="Target_Child"))
# 
# 
# #make sure that all children have the 4 categories ,if not mark as 0
# #CDS
# table(sum_demuth_CDS$keychild,sum_demuth_CDS$speaker) #check
# #create the lines (this should be done via a loop sorry!)
# peer_Hlo <- data.frame("sibling","Hlobohang", "0", "CDS")
# #names the lines
# names(peer_Hlo)<-c("speaker","keychild", "nb_utt","input")
# neww <- rbind(sum_demuth_CDS, peer_Hlo)
# #added to the main data.frame
# sum_demuth_CDS <- rbind(sum_demuth_CDS, peer_Hlo)
# 
# 
# #ADS
# table(sum_demuth_ADS$keychild,sum_demuth_ADS$speaker) #check
# #create the lines (this should be done via a loop sorry!)
# peer_Hlo <- data.frame("sibling","Hlobohang", "0", "ADS")
# #names the lines
# names(peer_Hlo)<-c("speaker","keychild", "nb_utt","input")
# neww <- rbind(sum_demuth_ADS, peer_Hlo)
# #added to the main data.frame
# sum_demuth_ADS <- rbind(sum_demuth_ADS, peer_Hlo)
# 
# demuth_fig <-rbind(sum_demuth_ADS,sum_demuth_CDS)
# trywells <- melt(sum_wells_ADS[,c("child","tot.adults", "tot.children")],id.vars = 1)
# colnames(dfm) <- c("child", "input", "value")
# dft <- melt(bigsum_low[,c("child","cds.adults", "cds.children")],id.vars = 1)
# colnames(dft) <- c("child", "input.cds", "value.cds")
# cbind(dfm,dft) -> try
# try[4] <- NULL
# merge(x=bigsum_low,y = try[ , c("child",  "input", "value", "input.cds", "value.cds"),], all.x=T,all.y=F)->try2
```


```{r figure making, eval=TRUE, include=TRUE, message=FALSE}
# 
# #not normalized / all corpus
# 
# 
# 
# 
# 
# 
# ggplot(sum_demuth_register, aes( y=nb_utt, x=keychild, fill=input))+ geom_bar(stat="identity", position="dodge")
# 
# Hlobohang <- ggplot(subset(sum_demuth_register_fig, keychild %in% c("Hlobohang") ), aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="dodge") +  labs(x="Hlobohang", y="")  + guides(fill=FALSE)
# 
# Litlhare <- ggplot(subset(sum_demuth_register_fig, keychild %in% c("Litlhare") ), aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="dodge") +  labs(x="Litlhare", y="Number of utterances")  + guides(fill=guide_legend(title=NULL))
# 
# Tsebo <- ggplot(subset(sum_demuth_register_fig, keychild %in% c("Tsebo") ), aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="dodge") +  labs(x="Tsebo", y="")  + guides(fill=FALSE)
# 
# 
# Hlobohang_stack<- ggplot(subset(sum_demuth_register, keychild %in% c("Hlobohang") ), aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="fill") +  labs(x="Hlobohang", y="")  + guides(fill=guide_legend(title=NULL))
# 
# Litlhare_stack<- ggplot(subset(sum_demuth_register, keychild %in% c("Litlhare") ), aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="fill") +  labs(x="Litlhare", y="Number of utterances")  + guides(fill=guide_legend(title=NULL))
# 
# Tsebo_stack <- ggplot(subset(sum_demuth_register, keychild %in% c("Tsebo") ), aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="fill") +  labs(x="Tsebo", y="")  + guides(fill=FALSE)
# #scale_fill_discrete(labels= c("Adults", "Mother", "Peers", "Siblings"))
# 
# #this plot for abstract
# Sesothofig<-ggplot(sum_demuth_register_fig, aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="dodge") +  labs(x="", y="")  + guides(fill=FALSE) + ggtitle("Sesotho")
# Frenchfig<-ggplot(sum_french_register_fig, aes( y=nb_utt, x=input, fill=speaker))+
#   geom_bar(stat="identity", position="dodge") +  labs(x="", y="")  + guides(fill=guide_legend(title=NULL)) + ggtitle("French")
# 
# png(filename="/Users/admin/Desktop/name.png", res=100, width=500)
# ggarrange(Sesothofig, Frenchfig, ncol=1, nrow=2, common.legend = TRUE, legend="bottom")
# dev.off()
# 
# 
# #this
# ggarrange(Hlobohang, Litlhare,Tsebo, ncol=1, nrow=3, common.legend = TRUE, legend="bottom")
# ggarrange(Hlobohang_stack, Litlhare_stack,Tsebo_stack, ncol=1, nrow=3, common.legend = TRUE, legend="bottom")
# 
# 
# #panel
# multiplot (wells_full, demuth_full, cols=1)
# multiplot (wells_annot, demuth_annot, cols=1)
#  

#fill <- multiplot (wells_CDS, demuth_CDS, cols=1) 
#dodge <- multiplot (Hlobohang, Litlhare,Tsebo, cols=1) 
```
