
---
  title             : "Peer speech project"
---

```{r demuth preparation, eval=TRUE, include=TRUE, message=FALSE}

###########Sesotho analysis starts here


lang<-"Sesotho"

#reads demuth corpus and counts utterances per speaker
demuth<-read.csv(file="sesotho_CDS_complete.csv", header=TRUE) # memory processing problems, can't load googlesheets
demuth<-subset(demuth, !(demuth$speaker_role_raw=="Target_Child")) #remove target child utterances

#mark corpus by keychild cs: I checked twice if someone wants to double check awesome
demuth$keychild <- NA
demuth$keychild[demuth$session_id %in% c(2414:2458)] <- "Hlobohang"
demuth$keychild[demuth$session_id %in% c(2459:2503)] <- "Litlhare"
demuth$keychild[demuth$session_id %in% c(2504:2542)] <- "Tsebo"

#verify annotations
demuthSecondAnnotations<-subset(demuth, !(demuth$annotation2==""))
length(which(demuthSecondAnnotations$Diff_annotations=="DIFFER"))/nrow(demuthSecondAnnotations)

demuthSecondAnnotationsChild1<-subset(demuthSecondAnnotations, (demuthSecondAnnotations$keychild=="Hlobohang"))
length(which(demuthSecondAnnotationsChild1$Diff_annotations=="DIFFER"))/nrow(demuthSecondAnnotationsChild1)
demuthSecondAnnotationsChild2<-subset(demuthSecondAnnotations, (demuthSecondAnnotations$keychild=="Litlhare"))
length(which(demuthSecondAnnotationsChild2$Diff_annotations=="DIFFER"))/nrow(demuthSecondAnnotationsChild2)
demuthSecondAnnotationsChild3<-subset(demuthSecondAnnotations,  (demuthSecondAnnotations$keychild=="Tsebo"))
length(which(demuthSecondAnnotationsChild3$Diff_annotations=="DIFFER"))/nrow(demuthSecondAnnotationsChild3)


#number of utterances per speaker
demuth$speaker <- NA
demuth$speaker[demuth$speaker_role_raw == "Mother"] <- "mother"
demuth$speaker[demuth$speaker_role_raw == "Investigator"] <- "investigator"
demuth$speaker[grep("Sister|Brother|Sibling", demuth$speaker_role_raw)]  <- "sibling"
demuth$speaker[grep("Child|Playmate|child|Teenager|Cousin", demuth$speaker_role_raw)]  <- "peer"
demuth$speaker[grep("Adult|Uncle|Grandmother|Family_Friend|Visitor|Aunt|Father", demuth$speaker_role_raw)]  <- "adult"
demuth$speaker[grep("Target", demuth$speaker_role_raw)] <- "Target_Child"

#save changes
write.table(demuth, file=paste0("/Users/admin/Desktop/demuth_input2.txt"), row.names=F, col.names=T,  quote=F) 

#Sum the number of utterances per speaker category and keychild
aggregate(demuth$utterance_id,by=list( demuth$speaker, demuth$keychild),length )->sum_demuth
colnames(sum_demuth) <- c("speaker", "keychild", "nb_utt")

#lenght demuth by child
trybis<- demuth %>% group_by(keychild) %>% summarise(no_rows = length(keychild)) 


```

```{r demuth directedness, eval=TRUE, include=TRUE, message=FALSE}

#ADRESSEE ANNOTATIONS PART

#Sum the number of utterances per speaker category and keychild and ADDRESSEE
nrow(demuth)
demuth<-subset(demuth, !(demuth$Diff_annotations=="DIFFER"))
demuth<-subset(demuth, !(demuth$annotation1=="?"))
nrow(demuth)

aggregate(demuth$utterance_id,by=list(demuth$annotation1,  demuth$speaker, demuth$keychild),length )->sum_demuth_addressee
colnames(sum_demuth_addressee) <- c("addresse", "speaker", "keychild", "nb_utt")

# Utterances addressed to the target child  aka CDS
demuth_CD<-subset(demuth, (demuth$annotation1==1))

aggregate(demuth_CD$utterance_id,by=list(demuth_CD$speaker, demuth_CD$keychild),length )->sum_demuth_CD
colnames(sum_demuth_CD) <- c( "speaker", "keychild", "nb_utt")

#classify into categories the different speakers 
demuth_CD$annotation1<-as.factor(demuth_CD$annotation1)
#total utterances 
total_demuth<-length(demuth$utterance_id) # 37843

##CREATE TABLE of different addressees in the corpus
demuth_table<- demuth %>% group_by(annotation1) %>% summarise(no_rows = length(annotation1))
demuth_table<-as.data.frame(demuth_table)
# re order by descending number
demuth_table<- demuth_table %>% arrange(desc(no_rows))
demuth_table


# Utterances addressed to the target child  aka CDS
demuth_CD_utt<- as.data.frame(demuth_CD %>%select(utterance))
write.table(demuth_CD_utt, file=paste0(lang, "Demuthchilddirected.txt"), row.names=F, col.names=T,  quote=F) 

#percentage of child directed speech vs total annotated
length(demuth_CD$utterance)/total_demuth *100 #79.8


#matches addressee with speaker roles (especially for non-child directed)
speaker_info_demuth<- as.data.frame(unique(demuth %>%select(uniquespeaker_id_fk, speaker_role_raw)))
colnames(speaker_info_demuth)[colnames(speaker_info_demuth)=="speaker_role_raw"] <- "role_adressee"
merged_speaker_info_demuth<-merge(x=demuth, y=speaker_info_demuth, by.x="annotation1", by.y="uniquespeaker_id_fk", all.x=TRUE, sort=TRUE)

# Utterances addressed to others - adults
demuth_adult_directed<-subset(merged_speaker_info_demuth, !(merged_speaker_info_demuth$role_adressee=="Playmate"| merged_speaker_info_demuth$role_adressee=="Cousin"|merged_speaker_info_demuth$annotation1=="PET"| merged_speaker_info_demuth$annotation1=="SELF"| merged_speaker_info_demuth$role_adressee=="Brother"| merged_speaker_info_demuth$annotation1=="NA"| merged_speaker_info_demuth$role_adressee=="Teenager"|merged_speaker_info_demuth$role_adressee=="Sister"|merged_speaker_info_demuth$annotation1=="1"|merged_speaker_info_demuth$annotation1=="0"|merged_speaker_info_demuth$annotation1=="O"|merged_speaker_info_demuth$annotation1=="TOY"|merged_speaker_info_demuth$annotation1=="RECORDER"))

# Utterances addressed to others - children
demuth_otherchild_directed<-subset(merged_speaker_info_demuth, !(merged_speaker_info_demuth$role_adressee=="Adult"| merged_speaker_info_demuth$role_adressee=="Father"|merged_speaker_info_demuth$annotation1=="PET"| merged_speaker_info_demuth$annotation1=="SELF"| merged_speaker_info_demuth$role_adressee=="Grandmother"| merged_speaker_info_demuth$annotation1=="NA"| merged_speaker_info_demuth$role_adressee=="Investigator"|merged_speaker_info_demuth$role_adressee=="Mother"|merged_speaker_info_demuth$annotation1=="1"|merged_speaker_info_demuth$annotation1=="0"|merged_speaker_info_demuth$role_adressee=="Uncle"|merged_speaker_info_demuth$annotation1=="TOY"|merged_speaker_info_demuth$annotation1=="RECORDER"))

aggregate(demuth_adult_directed$utterance_id,by=list(demuth_adult_directed$speaker, demuth_adult_directed$keychild),length )->sum_demuth_ADS
colnames(sum_demuth_ADS) <- c( "speaker", "keychild", "nb_utt")

aggregate(demuth_otherchild_directed$utterance_id,by=list(demuth_otherchild_directed$speaker, demuth_otherchild_directed$keychild),length )->sum_demuth_OCDS
colnames(sum_demuth_ADS) <- c( "speaker", "keychild", "nb_utt")

#subset all utterances marked as ADS & OCDS
demuth_ad_directed_utts<- as.data.frame(demuth_adult_directed %>%select(utterance))
demuth_oc_directed_utts<- as.data.frame(demuth_otherchild_directed %>%select(utterance))
#export all ADS utterance into a text file
write.table(demuth_ad_directed_utts, file=paste0("Sesothoadultdirected"), row.names=F, col.names=T,  quote=F) 
write.table(demuth_oc_directed_utts, file=paste0("Sesothootherchilddirected"), row.names=F, col.names=T,  quote=F) 


#percentage of adult directed speech vs total annotated
length(demuth_adult_directed$utterance)/total_demuth *100 #7.4
length(demuth_otherchild_directed$utterance)/total_demuth *100 #11.6

``` 

```{r demuth sentence type, eval=TRUE, include=TRUE, message=FALSE}

#Utterances type analysis

#Utterances marked as CDS
demuth_sentence_type_CD<- demuth_CD %>% group_by(sentence_type) %>% summarise(no_rows = length(sentence_type))
#Utterances marked as questions
directed_questions<-subset(demuth_sentence_type_CD, (demuth_sentence_type_CD$sentence_type=="question"))
#percentage marked as questions in CDS annotated corpus 
directed_questions$no_rows/sum(demuth_sentence_type_CD$no_rows) *100 #36.56

#Sentences marked as ADS
demuth_sentence_type_AD<- demuth_adult_directed %>% group_by(sentence_type) %>% summarise(no_rows = length(sentence_type))
#Utterances marked as questions
adultdirected_questions<-subset(demuth_sentence_type_AD, (demuth_sentence_type_AD$sentence_type=="question"))
#percentage marked as questions in ADS annotated corpus 
adultdirected_questions$no_rows/sum(demuth_sentence_type_AD$no_rows)*100 #14.97


```

```{r demuth for figure purposes}

library(reshape2)

#add label of type of input
sum_demuth_ADS$input <- "ADS"
sum_demuth_CDS$input <- "CDS"

#remove for CDS the target child utterances in which he is talking to himself
sum_demuth_CDS<-subset(sum_demuth_CDS, !(sum_demuth_CDS$speaker=="Target_Child"))
sum_demuth_ADS<-subset(sum_demuth_ADS, !(sum_demuth_ADS$speaker=="Target_Child"))


#make sure that all children have the 4 categories ,if not mark as 0
#CDS
table(sum_demuth_CDS$keychild,sum_demuth_CDS$speaker) #check
#create the lines (this should be done via a loop sorry!)
peer_Hlo <- data.frame("sibling","Hlobohang", "0", "CDS")
#names the lines
names(peer_Hlo)<-c("speaker","keychild", "nb_utt","input")
neww <- rbind(sum_demuth_CDS, peer_Hlo)
#added to the main data.frame
sum_demuth_CDS <- rbind(sum_demuth_CDS, peer_Hlo)


#ADS
table(sum_demuth_ADS$keychild,sum_demuth_ADS$speaker) #check
#create the lines (this should be done via a loop sorry!)
peer_Hlo <- data.frame("sibling","Hlobohang", "0", "ADS")
#names the lines
names(peer_Hlo)<-c("speaker","keychild", "nb_utt","input")
neww <- rbind(sum_demuth_ADS, peer_Hlo)
#added to the main data.frame
sum_demuth_ADS <- rbind(sum_demuth_ADS, peer_Hlo)

demuth_fig <-rbind(sum_demuth_ADS,sum_demuth_CDS)

# trywells <- melt(sum_wells_ADS[,c("child","tot.adults", "tot.children")],id.vars = 1)
# colnames(dfm) <- c("child", "input", "value")
# dft <- melt(bigsum_low[,c("child","cds.adults", "cds.children")],id.vars = 1)
# colnames(dft) <- c("child", "input.cds", "value.cds")
# cbind(dfm,dft) -> try
# try[4] <- NULL
# merge(x=bigsum_low,y = try[ , c("child",  "input", "value", "input.cds", "value.cds"),], all.x=T,all.y=F)->try2



```


```{r wells preparation, eval=TRUE, include=TRUE, message=FALSE}

#load Wells data

lang<-"English"
wells<-read.csv(file="/Users/lscpuser/Documents/peerproject/peerproject/wells.csv", header=T) #11,866
wells[6]<-NULL

#mark corpus by keychild cs: I checked twice i someone wants to double check awesome
wells$keychild <- NA
wells$keychild [1:2278] <- "benjamin"
wells$keychild [2279:3400] <- "samantha"
wells$keychild [3401:3962] <- "debbie"
wells$keychild [3963:4776] <- "sheila"
wells$keychild [4777:5601] <- "stella"
wells$keychild [5602:7224] <- "abigail"
wells$keychild [7225:9038] <- "geoffrey"
wells$keychild [9039:10909] <- "harriet"
wells$keychild [10910:11866] <- "laura"

#add gender
wells$gender [wells$keychild == "benjamin"] <- "M"
wells$gender [wells$keychild == "samantha"] <- "F"
wells$gender [wells$keychild == "debbie"] <- "F"
wells$gender [wells$keychild == "samantha"] <- "F"
wells$gender [wells$keychild == "sheila"] <- "F"
wells$gender [wells$keychild == "stella"] <- "F"
wells$gender [wells$keychild == "abigail"] <- "F"
wells$gender [wells$keychild == "geoffrey"] <- "M"
wells$gender [wells$keychild == "harriet"] <- "F" #assuming girl
wells$gender [wells$keychild == "laura"] <- "F"


#remove target child utts  aka 4,830 entries
#wells_input<- wells[!grepl("Target", wells$ROLE),] 
wells$speaker[wells$ROLE == "Mother"] <- "mother"
wells$speaker[grep("Sister|Brother|Sibling", wells$ROLE)]  <- "sibling"
wells$speaker[grep("Child|Playmate|child", wells$ROLE)]  <- "peer"
wells$speaker[grep("Adult|Uncle|Grandmother|Family_Friend|Visitor|Aunt|Father", wells$ROLE)]  <- "adult"
wells$speaker[grep("Target", wells$ROLE)] <- "Target_Child"


#name and save data
colnames(wells)<-c("NAME"   ,   "ROLE"   ,   "UTTERANCE", "COMMENT"  , "DIRECTED"    ,  "keychild" , "gender"   , "speaker")

wells[] <- lapply(wells, gsub, pattern='\t', replacement='')

write.table(wells, file=paste0("wells_input.csv"), row.names=F, col.names=T,  quote=F, sep='\t') 

#Sum the number of utterances per speaker category and keychild
aggregate(wells$UTTERANCE,by=list( wells$speaker, wells$keychild),length )->sum_wells
colnames(sum_wells) <- c("speaker", "keychild", "nb_utt")


try<- wells %>% group_by(keychild) %>% summarise(no_rows = length(keychild)) # 11866

#

``` 

```{r wells directedness, include=TRUE, message=FALSE}

#NOT WORKING FOR SOME REASON:
read.table("wells_input.csv",header=F, sep='\t', fill = TRUE)->wells_input
colnames(wells_input)<-c("NAME"   ,   "ROLE"   ,   "UTTERANCE", "COMMENT"  , "DIRECTED"    ,  "keychild" , "gender"   , "speaker")

#ADRESSEE ANNOTATIONS PART  #6785 ~ 57.2%
wells_annotated_input<-subset(wells, !(wells$DIRECTED=="")) #select utterances annotated by Naomi Alex up to now , for now 3098 rows PLEASE UPDATE as we go !!

#Sum the number of utterances per speaker category and keychild
aggregate(wells_annotated_input$UTTERANCE,by=list( wells_annotated_input$speaker, wells_annotated_input$keychild),length )->sum_wells_annotated
colnames(sum_wells_annotated) <- c("speaker", "keychild", "nb_utt")


#Sum the number of utterances per speaker category and keychild and ADDRESSEE
aggregate(wells_annotated_input$UTTERANCE,by=list(wells_annotated_input$DIRECTED,  wells_annotated_input$speaker, wells_annotated_input$keychild),length )->sum_wells_addressee
colnames(sum_wells_addressee) <- c("addresse", "speaker", "keychild", "nb_utt")

# Utterances addressed to the target child  aka CDS 2181*100/6785 = 32%
wells_child_directed<-subset(wells_annotated_input, (wells_annotated_input$DIRECTED=="CHI"))

aggregate(wells_child_directed$UTTERANCE,by=list(wells_child_directed$speaker, wells_child_directed$keychild),length )->sum_wells_CDS
colnames(sum_wells_CDS) <- c( "speaker", "keychild", "nb_utt")
write.table(sum_wells_CDS, file=paste0("sum_wells_CDS.txt"), row.names=F, col.names=T,  quote=F) 


#subset all utterances marked as CDS
wells_child_directed<-subset(wells_child_directed, !(wells_child_directed$speaker=="Target_Child"))

wells_cd_directed_utts<- as.data.frame(wells_child_directed %>%select(UTTERANCE))
#export all CDS utterance into a text file
write.table(wells_cd_directed_utts, file=paste0( lang,"Wellschilddirected.txt"), row.names=F, col.names=T,  quote=F) 


# Utterances addressed to adults aka ADS

#for this it needed to know the corpus quite well... So I'm assuming that LOU - REB - RAC - CHR - 0 - NIC ARE NOT ADULTS right???
#group of children that is not target child
well_adult_directed<-subset(wells_annotated_input, !(wells_annotated_input$DIRECTED=="CHI" |wells_annotated_input$DIRECTED=="0" |wells_annotated_input$DIRECTED=="O" | wells_annotated_input$DIRECTED=="?" | wells_annotated_input$DIRECTED=="SELF"| wells_annotated_input$DIRECTED=="NIC"  | wells_annotated_input$DIRECTED=="TELEPHONE" | wells_annotated_input$DIRECTED=="MIX" | wells_annotated_input$DIRECTED=="LOU" | wells_annotated_input$DIRECTED=="REB" | wells_annotated_input$DIRECTED=="PET"| wells_annotated_input$DIRECTED=="RAC" | wells_annotated_input$DIRECTED=="CHR" | wells_annotated_input$DIRECTED=="NA"))

aggregate(well_adult_directed$UTTERANCE,by=list(well_adult_directed$speaker, well_adult_directed$keychild),length )->sum_wells_ADS
colnames(sum_wells_ADS) <- c( "speaker", "keychild", "nb_utt")
write.table(sum_wells_ADS, file=paste0("sum_wells_ADS.txt"), row.names=F, col.names=T,  quote=F) 


well_adult_directed<-subset(well_adult_directed,!(well_adult_directed$ROLE=="Target_Child"))
#subset all utterances marked as ADS
wells_ad_directed_utts<- as.data.frame(well_adult_directed %>%select(UTTERANCE))
wells_ad_directed_uttstarget<- as.data.frame(well_adult_directed %>%select(UTTERANCE, keychild))

#export all ADS utterance into a text file
write.table(wells_ad_directed_utts, file=paste0(lang, "Wellsadultdirected.txt"), row.names=F, col.names=T,  quote=F) 

write.table(well_adult_directed, file=paste0(lang, "Wellsalladultdirected.txt"), row.names=F, col.names=T,  quote=F) 


```

```{r wells for figure purposes}

library(reshape2)

#add label of type of input
sum_wells_ADS$input <- "ADS"
sum_wells_CDS$input <- "CDS"

#remove for CDS the target child utterances in which he is talking to himself
sum_wells_CDS<-subset(sum_wells_CDS, !(sum_wells_CDS$speaker=="Target_Child"))
sum_wells_ADS<-subset(sum_wells_ADS, !(sum_wells_ADS$speaker=="Target_Child"))


#make sure that all children have the 4 categories ,if not mark as 0
#CDS
table(sum_wells_CDS$keychild,sum_wells_CDS$speaker) #check
#create the lines (this should be done via a loop sorry!)
peer_abi <- data.frame("peer","abigail", "0", "CDS")
peer_benji<- data.frame("peer","benjamin", "0", "CDS")
#names the lines
names(peer_abi)<-c("speaker","keychild", "nb_utt","input")
names(peer_benji)<-c("speaker","keychild", "nb_utt","input")
new <- rbind(peer_abi, peer_benji)
#added to the main data.frame
sum_wells_CDS <- rbind(sum_wells_CDS, new)


#ADS
table(sum_wells_ADS$keychild,sum_wells_ADS$speaker) #check
#create the lines (this should be done via a loop sorry!)
peer_abi <- data.frame("peer","abigail", "0", "ADS")
peer_benji<- data.frame("peer","benjamin", "0", "ADS")
adult_geof <- data.frame("adult","geoffrey", "0", "ADS")
#names the lines
names(peer_abi)<-c("speaker","keychild", "nb_utt","input")
names(peer_benji)<-c("speaker","keychild", "nb_utt","input")
names(adult_geof)<-c("speaker","keychild", "nb_utt","input")

new <- rbind(peer_abi, peer_benji,adult_geof)
#added to the main data.frame
sum_wells_ADS <- rbind(sum_wells_ADS, new)

wells_fig <-rbind(sum_wells_ADS,sum_wells_CDS)

# trywells <- melt(sum_wells_ADS[,c("child","tot.adults", "tot.children")],id.vars = 1)
# colnames(dfm) <- c("child", "input", "value")
# dft <- melt(bigsum_low[,c("child","cds.adults", "cds.children")],id.vars = 1)
# colnames(dft) <- c("child", "input.cds", "value.cds")
# cbind(dfm,dft) -> try
# try[4] <- NULL
# merge(x=bigsum_low,y = try[ , c("child",  "input", "value", "input.cds", "value.cds"),], all.x=T,all.y=F)->try2



```

```{r percentages-wells, eval=FALSE }
# count different types of addressees 
wells_annotated_value<- wells_annotated_input %>% group_by(DIRECTED) %>% summarise(no_rows = length(DIRECTED))
#create a data.frame
wells_annotated_value<-as.data.frame(wells_annotated_value)
#Number of number  of utts that have annotated adressees
wells_total_annotated_input<-sum(wells_annotated_value$no_rows)  #2059
wells_annotated_value

# Utterances addressed to the target child  aka CDS
wells_child_directed<-subset(wells_annotated_input, (wells_annotated_input$DIRECTED=="CHI")) #wells annotated child-directed corpus
# n of child-directed utterances
length(wells_child_directed$UTTERANCE)/ length(wells_annotated_input$UTTERANCE)  * 100 #45.07042

 # n of adult directed utterances
length(wells_ad_directed_utts$UTTERANCE)/ length(wells_annotated_input$UTTERANCE) * 100 #22.38951 %

#NA annotations
#cs: whart about 0 ???
wells_annotated_na <- subset(wells_annotated_input,(wells_annotated_input$DIRECTED=="?"|wells_annotated_input$DIRECTED=="NA"|wells_annotated_input$DIRECTED==""|wells_annotated_input$DIRECTED==" "))
length(wells_annotated_na$UTTERANCE)/ length(wells_annotated_input$UTTERANCE) *100 # 5.68237 % 


```

```{r figure making, eval=TRUE, include=TRUE, message=FALSE}

#install libraries
library(ggplot2)
library(scales)
library(gridExtra)

#defining multiplot
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

#not normalized / all corpus
wells_full <- ggplot(sum_wells, aes( y=nb_utt, x=keychild, fill=speaker))+
  geom_bar(stat="identity", position="dodge")
demuth_full <- ggplot(sum_demuth, aes( y=nb_utt, x=keychild, fill=speaker))+
  geom_bar(stat="identity", position="dodge")

#not normalized / all corpus
wells_annot<- ggplot(sum_wells_annotated, aes( y=nb_utt, x=keychild, fill=speaker))+
  geom_bar(stat="identity", position="dodge")
demuth_annot<- ggplot(sum_demuth_annotated, aes( y=nb_utt, x=keychild, fill=speaker))+
  geom_bar(stat="identity", position="dodge")



wells_addresse<- ggplot(sum_wells_addressee, aes( y=nb_utt, x=keychild, fill=addresse))+
  geom_bar(stat="identity", position="dodge")
demuth_addresse<- ggplot(sum_demuth_addressee, aes( y=nb_utt, x=keychild, fill=addresse))+
  geom_bar(stat="identity", position="dodge")


#remove catherine for plot
demuth_fig<-subset(demuth_fig, !(demuth_fig$speaker=="investigator"))




#this is the code for the figuresss

wells_ADSCDS<- ggplot(wells_fig, aes( y=as.numeric(nb_utt), x=input, fill=speaker))+
  geom_bar(stat="identity", position="dodge") +  labs(x="Wells Corpus", y="Number of utterances") + guides(fill=guide_legend(title=NULL))
demuth_ADSCDS<- ggplot(demuth_fig, aes( y=as.numeric(nb_utt), x=input, fill=speaker))+
  geom_bar(stat="identity", position="dodge") +  labs(x="Demuth Corpus", y="Number of utterances") + scale_fill_discrete(labels= c("Adults", "Mother", "Peers", "Siblings")) + guides(fill=guide_legend(title=NULL))




#panel
 # multiplot (wells_full, demuth_full, cols=1)
 # multiplot (wells_annot, demuth_annot, cols=1)
 #  
  
 #fill <- multiplot (wells_CDS, demuth_CDS, cols=1) 
 dodge <- multiplot (wells_ADSCDS, demuth_ADSCDS, cols=1) 
 
```
